name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Review Action
        uses: freeedcom/ai-codereviewer@v2.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
